# Generated by Django 5.0.4 on 2024-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='have_wheels',
            field=models.BooleanField(default=False),
        ),
    ]
