# Generated by Django 5.0.4 on 2024-05-07 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_have_wheels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ER', 'Em Revisão'), ('D', 'Disponível'), ('I', 'Indisponível')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.color', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='have_wheels',
            field=models.BooleanField(default=False, verbose_name='Possui Rodas'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_year',
            field=models.CharField(max_length=10, verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.type', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='wheels_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Rodas'),
        ),
    ]
