# Generated by Django 5.0.4 on 2024-05-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
